version: 2
updates:
  # npm（アプリ本体）
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"    # 毎日
      time: "06:00"        # UTC（= 日本時間 15:00）
    open-pull-requests-limit: 10
    versioning-strategy: increase # ^1.2.3 -> 1.3.0 などにアップデート
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    dev-deps:
      patterns:
        - "@types/*"
        - "eslint*"

  # GitHub Actions (CI)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message: