name: dependabot-auto-merge

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

# GITHUB_TOKEN の既定権限を上書き（このワークフロー限定）
permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Convert draft to ready (Dependabot)
        uses: peter-evans/convert-draft-to-ready@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
