name: dependabot-auto-merge

on:
  # Dependabot が作る PR に対して発火（イベントをユニオン）
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, ready_for_review]

# 自動マージに必要な権限
permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Dependabot の PR のみ対象
    if: github.actor == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      # 1) Auto-merge を有効化（GitHub の自動マージフラグを立てる）
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      # 2) すべての必須チェックが success になるまで待機
      - name: Wait for all required checks to pass
        uses: lewagon/wait-on-check-action@v1.3.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: dependabot-auto-merge
          wait-interval: 10
          allowed-conclusions: success

      # 3) フォールバック：未マージなら手動で squash merge を実行
      - name: Merge when green (fallback)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data: prData } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            if (prData.merged) {
              core.info(`PR #${pr.number} already merged.`);
            } else {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash',
              });
              core.info(`PR #${pr.number} merged.`);
            }