# .github/workflows/dependabot-auto-merge.yml
name: dependabot-auto-merge

on:
  # Dependabot が作る PR に対して発火
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, ready_for_review]

# 自動マージに必要な権限
permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Dependabot が作った PR のときだけ動く
    if: >
      github.actor == 'dependabot[bot]' ||
      (github.event.pull_request.user.login == 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      # 0) ブランチ保護に対応するため自動承認
      - name: Auto-approve Dependabot PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # 1) GitHub の Auto-merge を有効化（squash）
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash

      # 2) すべての必須チェックが success になるまで待つ（この WF 自身は除外）
      - name: Wait for required checks
        uses: lewagon/wait-on-check-action@v1.3.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: dependabot-auto-merge
          wait-interval: 10
          allowed-conclusions: success

      # 3) フォールバック：未マージなら API で squash merge
      - name: Merge when green (fallback)
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            if (data.merged) {
              core.info(`PR #${pr.number} already merged ✅`);
              return;
            }
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash',
              });
              core.info(`PR #${pr.number} merged via API ✅`);
            } catch (e) {
              core.warning(`Fallback merge failed: ${e.message}`);
            }